const TIMEFRAMES = ['1m', '5m', '15m', '1h', '4h', '1d'];
const API_BASE = window.location.origin;
const FAVORITES_KEY = 'trade_sentinel_favorites';
const state = { assets: [], selected: [], timeframe: '15m', analyses: [], activeSymbol: '', loading: false, alertsEnabled: false, lastScan: '', q: '', category: 'All', exchange: 'All', page: 1, limit: 40, hasMore: false, total: 0, categories: [], exchanges: [], favorites: new Set(JSON.parse(localStorage.getItem(FAVORITES_KEY) || '[]')) };
const esc = (v) => String(v).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));

async function init() { render(); await loadAssets(); if (!state.selected.length && state.assets[0]) state.selected = [state.assets[0].symbol]; await scan(); setInterval(scan, 90000); }
async function loadAssets() {
  const params = new URLSearchParams({ q: state.q, category: state.category, exchange: state.exchange, page: String(state.page), limit: String(state.limit) });
  const r = await fetch(`${API_BASE}/api/assets?${params}`); const d = await r.json(); state.assets = d.assets || []; state.hasMore = !!d.hasMore; state.total = d.total || 0; state.categories = d.categories || []; state.exchanges = d.exchanges || [];
}
async function scan() { if (!state.selected.length) return; state.loading = true; render(); const r = await fetch(`${API_BASE}/api/scan?symbols=${state.selected.join(',')}&interval=${state.timeframe}`); const d = await r.json(); state.analyses = d.results || []; state.activeSymbol = state.activeSymbol && state.analyses.some((i) => i.asset.symbol === state.activeSymbol) ? state.activeSymbol : state.analyses[0]?.asset.symbol || ''; state.lastScan = new Date(d.generatedAt || Date.now()).toLocaleTimeString(); state.loading = false; render(); }

function render() {
  const active = state.analyses.find((x) => x.asset.symbol === state.activeSymbol) || state.analyses[0];
  document.getElementById('root').innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-icon">✦</div><div><strong>Trade Sentinel</strong><span>AI analysis only</span></div></div><div class="no-trade-card"><strong>No auto-trading</strong><p>Manual execution only.</p></div></aside><main><header class="hero"><div><span class="eyebrow">● Dynamic global market database</span><h1>Scan thousands of symbols with search, filters, favorites, and analysis.</h1></div><div class="hero-actions"><button class="primary" data-action="scan">${state.loading ? 'Scanning...' : 'Scan markets'}</button></div></header>
<section class="control-grid"><div class="panel asset-panel"><div class="panel-title"><span>Universe</span><small>${state.total} available</small></div><div class="search-row"><input id="search" placeholder="Search ticker/company (AAPL, TSLA, NIFTY, GOLD, BTCUSD)" value="${esc(state.q)}" /><select id="category">${(state.categories.length?state.categories:['All','Stocks','Futures','Forex','Crypto','Indices','ETFs']).map((c)=>`<option ${state.category===c?'selected':''}>${c}</option>`).join('')}</select><select id="exchange">${(state.exchanges.length?state.exchanges:['All']).map((e)=>`<option ${state.exchange===e?'selected':''}>${e}</option>`).join('')}</select></div><div class="asset-list">${state.assets.map(a=>`<button class="asset ${state.selected.includes(a.symbol)?'active':''}" data-asset="${esc(a.symbol)}"><strong>${esc(a.symbol)}</strong><span>${esc(a.type)} • ${esc(a.exchange||'')}</span><em class="fav" data-fav="${esc(a.symbol)}">${state.favorites.has(a.symbol)?'★':'☆'}</em></button>`).join('')}</div><div class="pager"><button data-page="prev" ${state.page===1?'disabled':''}>Prev</button><span>Page ${state.page}</span><button data-page="next" ${!state.hasMore?'disabled':''}>Next</button></div></div>
<div class="panel timeframe-panel"><div class="panel-title"><span>Timeframe</span><small>${state.selected.length} selected</small></div><div class="timeframes">${TIMEFRAMES.map(tf=>`<button data-timeframe="${tf}" class="${state.timeframe===tf?'active':''}">${tf}</button>`).join('')}</div><div class="favorites"><h4>Watchlist</h4>${[...state.favorites].map(s=>`<button class="chip" data-watch="${esc(s)}">${esc(s)}</button>`).join('')||'<span class="muted-copy">No favorites yet.</span>'}</div></div></section>
<section class="dashboard-grid"><div class="panel leaderboard"><div class="panel-title"><span>Opportunity Scanner</span><small>${state.lastScan||'—'}</small></div>${state.analyses.map(i=>`<button class="setup-row ${state.activeSymbol===i.asset.symbol?'active':''}" data-symbol="${esc(i.asset.symbol)}"><div><strong>${esc(i.asset.symbol)}</strong><span>${esc(i.asset.name)}</span></div><div class="bias">${i.setup.direction}</div><div class="confidence"><span style="width:${i.setup.confidence}%"></span><em>${i.setup.confidence}%</em></div></button>`).join('')}</div>${active?renderDesk(active):'<div class="panel empty">Select symbols and scan.</div>'}</section><section class="panel disclaimer"><p><strong>Risk disclaimer:</strong> Trading is risky. Suggestions are probabilistic and not guaranteed.</p></section></main></div>`;
  bind();
}
function renderDesk(a){return `<div class="trade-desk"><div class="panel chart-panel"><div class="panel-title"><span>${esc(a.asset.symbol)} visual trade chart</span><small>${esc(a.asset.type)} • ${esc(a.dataSource)}</small></div><div class="chart-wrap">${renderChart(a.candles,a.setup)}</div></div><div class="setup-details"><div class="panel ticket"><h2>${a.setup.direction}</h2><div class="levels"><div><span>Entry</span><strong>${a.setup.entry.toFixed(2)}</strong></div><div><span>Stop</span><strong>${a.setup.stop.toFixed(2)}</strong></div><div><span>Target</span><strong>${a.setup.target.toFixed(2)}</strong></div><div><span>R:R</span><strong>1:${a.setup.riskReward}</strong></div></div></div><div class="panel explanation"><ul>${a.setup.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div></div></div>`}
function renderChart(c,s){const w=920,h=420,p={top:22,right:96,bottom:34,left:28}; const vals=c.flatMap(x=>[x.close,x.sma20,x.sma50]).filter(Number.isFinite).concat([s.entry,s.stop,s.target,s.levels.support,s.levels.resistance]); const min=Math.min(...vals),max=Math.max(...vals),span=max-min||1; const x=(i)=>p.left+(i/Math.max(1,c.length-1))*(w-p.left-p.right), y=(v)=>h-p.bottom-((v-min)/span)*(h-p.top-p.bottom); const path=(k)=>c.map((v,i)=>Number.isFinite(v[k])?`${i?'L':'M'}${x(i).toFixed(1)},${y(v[k]).toFixed(1)}`:'').join(' '); const line=(v,cl,lb)=>`<line class="${cl}" x1="${p.left}" x2="${w-p.right}" y1="${y(v)}" y2="${y(v)}"/><text class="chart-label ${cl}" x="${w-p.right+8}" y="${y(v)+4}">${lb} ${v.toFixed(2)}</text>`; return `<svg viewBox="0 0 ${w} ${h}"><path class="area" d="${path('close')} L${x(c.length-1)},${h-p.bottom} L${p.left},${h-p.bottom} Z"/><path class="price-line" d="${path('close')}"/><path class="sma20" d="${path('sma20')}"/><path class="sma50" d="${path('sma50')}"/>${line(s.entry,'entry-line','ENTRY')}${line(s.stop,'stop-line','STOP')}${line(s.target,'target-line','TARGET')}</svg>`}

function bind(){document.querySelector('[data-action="scan"]')?.addEventListener('click',scan);document.querySelectorAll('[data-asset]').forEach(b=>b.addEventListener('click',()=>{const s=b.dataset.asset;state.selected=state.selected.includes(s)?state.selected.filter(x=>x!==s):[...state.selected,s].slice(-20);scan();}));document.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>{state.activeSymbol=b.dataset.symbol;render();}));document.querySelectorAll('[data-timeframe]').forEach(b=>b.addEventListener('click',()=>{state.timeframe=b.dataset.timeframe;scan();}));document.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',(e)=>{e.stopPropagation();const s=b.dataset.fav;state.favorites.has(s)?state.favorites.delete(s):state.favorites.add(s);localStorage.setItem(FAVORITES_KEY,JSON.stringify([...state.favorites]));render();}));document.querySelectorAll('[data-watch]').forEach(b=>b.addEventListener('click',()=>{const s=b.dataset.watch;if(!state.selected.includes(s))state.selected=[...state.selected,s].slice(-20);scan();}));document.getElementById('search')?.addEventListener('change', async (e)=>{state.q=e.target.value.trim();state.page=1;await loadAssets();render();});document.getElementById('category')?.addEventListener('change', async (e)=>{state.category=e.target.value;state.page=1;await loadAssets();render();});document.getElementById('exchange')?.addEventListener('change', async (e)=>{state.exchange=e.target.value;state.page=1;await loadAssets();render();});document.querySelector('[data-page="prev"]')?.addEventListener('click',async()=>{state.page=Math.max(1,state.page-1);await loadAssets();render();});document.querySelector('[data-page="next"]')?.addEventListener('click',async()=>{if(!state.hasMore)return;state.page+=1;await loadAssets();render();});}
init();
